Repository anonklub/anonklub, pull requests merged in 2022-12, with the labels that each got.

#49 fix circom ecdsa relative imports
  circuits/circom/.gitignore
  circuits/circom/maybe-fix-circom-imports.sh
  circuits/circom/package.json
Labels: bug

#56 Prove set membership with ECDSA in circom
  .eslintrc.yaml
  .github/workflows/coveralls.yaml
  .gitignore
  README.md
  apis/query/package.json
  circuits/circom/.gitignore
  circuits/circom/maybe-fix-circom-imports.sh
  circuits/circom/membership.circom
  circuits/circom/merkleTree.circom
  circuits/circom/package.json
  circuits/circom/test/circuit.test.ts
  circuits/circom/test/helpers.ts
  circuits/circom/test/membership_test.circom
  circuits/circom/test/merkle_tree_test.circom
  circuits/circom/tsconfig.json
  circuits/halo2/.gitkeep
  package.json
  pnpm-lock.yaml
Labels: enhancement

#64 :recycle: Test circom circuits with `jest` instead of `chai`
  circuits/circom/jest.config.ts
  circuits/circom/package.json
  circuits/circom/test/circuit.test.ts
  circuits/circom/tsconfig.json
  jest.config.ts
  package.json
  pnpm-lock.yaml
Labels: dx, test
