Repository anonklub/anonklub, pull requests merged in 2023-06, with the labels that each got.

#188 :wrench: Update next.config.js
  pnpm-lock.yaml
  ui/.eslintrc.yaml
  ui/next.config.js
  ui/package.json
  ui/src/app/layout.tsx
  ui/src/app/verify/result/page.tsx
Labels: bug

#194 :recycle: use `snarkjs` node dep instead of command
  .gitignore
  apis/prove/package.json
  apis/prove/src/mq/processor.ts
  apis/prove/src/mq/queue.ts
  circuits/circom/README.md
  circuits/circom/test/data/input.json
  circuits/circom/test/data/proof.json
  circuits/circom/test/data/public.json
  package.json
  pnpm-lock.yaml
Labels: enhancement

#190 :rocket: Manage prove api deployment on aws with `pulumi`
  .barrelsby.json
  .eslintrc.yaml
  .tool-versions
  README.md
  apis/prove/package.json
  infra/.gitignore
  infra/Pulumi.dev.yaml
  infra/Pulumi.yaml
  infra/README.md
  infra/index.ts
  infra/package-lock.json
  infra/package.json
  infra/resources/ami.ts
  infra/resources/config.ts
  infra/resources/ec2-instance/index.ts
  infra/resources/ec2-instance/user-data.sh
  infra/resources/elastic-ip.ts
  infra/resources/index.ts
  infra/resources/ssh-key.ts
  infra/tsconfig.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: :building_construction: Infra

#185 :sparkles: Warn user about sec./privacy risks before submitting proof request
  ui/src/app/prove/prepare/from-file/page.tsx
  ui/src/components/HelpModal.tsx
  ui/src/components/SubmitProofRequest.tsx
  ui/src/components/WarningModal.tsx
  ui/src/components/index.ts
  ui/src/hooks/useStore.ts
  ui/src/store.ts
Labels: enhancement

#166 Update docs
  docs/docs/circuit-design.md
  docs/docs/intro.md
  docs/docs/long/generate-zk-proof.md
  docs/docs/long/verify.md
  docs/docusaurus.config.js
  pm/product-vision.md
Labels: documentation

#213 :construction_worker: Update GH test workflow trigger paths
  .github/workflows/test.yml
  .prettierignore
  contracts/src/Counter.sol
  foundry.toml
  turbo.json
Labels: test

#211 Update circuit-design.md
  docs/docs/circuit-design.md
Labels: documentation

#210 Update intro.md
  docs/docs/intro.md
Labels: documentation
