Repository anonklub/anonklub, pull requests merged in 2024-02, with the labels that each got.

#350 feat(ui): validate amount input in eth query form
  ui/src/app/query/asset/eth/page.tsx
Labels: enhancement

#351 feat(query-api): cache query results
  pnpm-lock.yaml
  query-api/package.json
  query-api/src/anonset.controller.ts
  query-api/src/anonset.module.ts
Labels: enhancement

#341 Adding git hooks
  .eslintignore
  .husky/pre-commit
  .lintstagedrc.json
  .prettierignore
  package.json
  pkgs/spartan-ecdsa-wasm/src/eth_membership.rs
  pnpm-lock.yaml
  ui/README.md
Labels: enhancement, :technologist: dx

#355 feat(ui): display error boundary for segments that fetch data server side
  ui/src/app/query/asset/nft/punk/error.tsx
  ui/src/app/query/beacon/error.tsx
Labels: enhancement, :lipstick: UI

#357 feat(ui): remove message to sign input field
  ui/src/components/SubmitProofRequest.tsx
  ui/src/hooks/useProofRequest.ts
  ui/src/lib/config.ts
Labels: :lipstick: UI

#347 Implement verify membership function
  ui/src/app/prove/result/page.tsx
  ui/src/app/verify/page.tsx
  ui/src/app/verify/result/page.tsx
  ui/src/components/JsonFileInput.tsx
  ui/src/components/ScrollableJsonContainer.tsx
  ui/src/components/SubmitProofRequest.tsx
  ui/src/hooks/useJsonFile.ts
  ui/src/hooks/useStore.ts
  ui/src/hooks/useVerifyProof.ts
  ui/src/lib/read-json-file.ts
  ui/src/store.ts
Labels: enhancement, needs rebase

#362 fix(ui): check against web worker initialization before having them "work"
  pnpm-lock.yaml
  ui/package.json
  ui/src/app/prove/result/page.tsx
  ui/src/app/verify/result/page.tsx
  ui/src/hooks/index.ts
  ui/src/hooks/useAsync.ts
  ui/src/hooks/useMerkleTreeWorker.ts
  ui/src/hooks/useProofRequest.ts
  ui/src/hooks/useProofResult.ts
  ui/src/hooks/useSpartanEcdsaWorker.ts
  ui/src/hooks/useVerifyProof.ts
  ui/src/hooks/useWorker.ts
Labels: bug, :lipstick: UI

#364 style: adjust buttons and modal colors & layout
  ui/src/app/layout.tsx
  ui/src/app/page.tsx
  ui/src/app/prove/page.tsx
  ui/src/app/prove/prepare/from-file/page.tsx
  ui/src/app/prove/prepare/from-on-chain/asset/nft/page.tsx
  ui/src/app/prove/prepare/from-on-chain/asset/page.tsx
  ui/src/app/prove/prepare/from-on-chain/dao/page.tsx
  ui/src/app/prove/prepare/from-on-chain/page.tsx
  ui/src/app/prove/result/page.tsx
  ui/src/app/prove/submit/page.tsx
  ui/src/app/query/asset/erc20/page.tsx
  ui/src/app/query/asset/eth/page.tsx
  ui/src/app/query/asset/nft/other/page.tsx
  ui/src/app/query/dao/ens/page.tsx
  ui/src/app/verify/page.tsx
  ui/src/app/verify/result/page.tsx
  ui/src/components/ConnectButton.tsx
  ui/src/components/Header.tsx
  ui/src/components/HelpModal.tsx
  ui/src/components/Loader.tsx
  ui/src/components/Modal.tsx
  ui/src/components/QuestionBox.tsx
  ui/src/components/Screen.tsx
  ui/src/components/SubmitProofRequest.tsx
  ui/src/components/Text.tsx
  ui/src/components/WarningModal.tsx
  ui/src/components/index.ts
  ui/src/globals.css
  ui/src/hooks/index.ts
  ui/src/hooks/useHelp.ts
  ui/src/hooks/useSetHelp.ts
  ui/src/hooks/useStore.ts
  ui/src/lib/read-json-file.ts
  ui/src/store.ts
Labels: :lipstick: UI

#373 feat: build `spartan-ecdsa-wasm` pkg with `--release` profile
  .prettierignore
  pkgs/merkle-tree-wasm/package.json
  pkgs/spartan-ecdsa-wasm/Cargo.toml
  pkgs/spartan-ecdsa-wasm/package.json
  pkgs/spartan-ecdsa-wasm/src/lib.rs
Labels: :electric_plug: circuits
