Repository anonklub/anonklub, pull requests merged in 2024-07, with the labels that each got.

#448 ci: optimize test workflow
  .github/workflows/main-staging.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
  .lintstagedrc.json
  package.json
Labels: ci/cd/ct

#442 Binary Merkle Tree Halo2 Gadget
  Cargo.lock
  Cargo.toml
  pkgs/binary-merkle-tree-halo2/Cargo.toml
  pkgs/binary-merkle-tree-halo2/README.md
  pkgs/binary-merkle-tree-halo2/package.json
  pkgs/binary-merkle-tree-halo2/src/binary_merkle_tree.rs
  pkgs/binary-merkle-tree-halo2/src/consts.rs
  pkgs/binary-merkle-tree-halo2/src/gadget.rs
  pkgs/binary-merkle-tree-halo2/src/lib.rs
Labels: circuits :electric_plug:

#455 ci: run test coverage in test-rs job
  .github/workflows/main-staging.yml
  .github/workflows/test-coverage.yaml
  pkgs/cli/tests/query.rs
  pkgs/spartan-ecdsa-wasm/src/utils.rs
Labels: bug :bug:, ci/cd/ct

#458 chore: use `lefthook` to manage git hooks
  .biome.jsonc
  .dprint.jsonc
  .github/ISSUE_TEMPLATE/sweep-template.yml
  .github/workflows/deploy-discord-bot-prod.yml
  .github/workflows/deploy-discord-bot-staging.yml
  .github/workflows/deploy-query-api-prod.yml
  .github/workflows/deploy-query-api-staging.yml
  .github/workflows/deploy-ui-prod.yml
  .github/workflows/deploy-ui-staging.yml
  .github/workflows/issue-link.yml
  .github/workflows/main-staging.yml
  .github/workflows/release.yml
  .knip.ts
  .lefthook.yml
  .lintstagedrc.json
  Cargo.toml
  discord-bot/fly-prod.toml
  discord-bot/fly-staging.toml
  foundry.toml
  package.json
  pkgs/binary-merkle-tree-halo2/Cargo.toml
  pkgs/circuits/halo2-secp256k1-wasm/Cargo.toml
  pkgs/circuits/halo2wrong-ecdsa/Cargo.toml
  pkgs/cli/Cargo.toml
  pkgs/merkle-tree-wasm/Cargo.toml
  pkgs/spartan-ecdsa-wasm/Cargo.toml
  pnpm-lock.yaml
  pnpm-workspace.yaml
  query-api/fly-prod.toml
  query-api/fly-staging.toml
  sweep.yaml
  ui/.dockerignore
  ui/.eslintrc.yaml
  ui/.gitignore
  ui/.prettierrc.js
  ui/fly-prod.toml
  ui/fly-staging.toml
  ui/package.json
  ui/src/globals.css
Labels: dx :technologist:

#460 ci: fix discord-bot deploy
  discord-bot/Dockerfile
  discord-bot/package.json
Labels: bug :bug:, ci/cd/ct

#461 ci: fix discord bot deployment
  .dockerignore
  .github/workflows/deploy-discord-bot-prod.yml
  .github/workflows/deploy-discord-bot-staging.yml
  discord-bot/Dockerfile
  discord-bot/package.json
Labels: ci/cd/ct, Infra :bricks:
