Repository anonklub/anonklub, pull requests merged in 2024-01, with the labels that each got.

#275 Implementing a wasm-pack liberary for merkle tree
  .gitignore
  .prettierignore
  Cargo.lock
  Cargo.toml
  merkle-tree-wasm/Cargo.toml
  merkle-tree-wasm/README.md
  merkle-tree-wasm/package.json
  merkle-tree-wasm/src/lib.rs
  merkle-tree-wasm/src/merkle_tree_wasm.rs
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo.json
Labels: enhancement

#285 Implmenting a web-worker for the rust merkle-tree wasm
  .eslintrc.yaml
  pnpm-lock.yaml
  pnpm-workspace.yaml
  workers/merkle-tree-worker/README.md
  workers/merkle-tree-worker/package.json
  workers/merkle-tree-worker/src/index.ts
  workers/merkle-tree-worker/src/interface.ts
  workers/merkle-tree-worker/src/worker.ts
  workers/merkle-tree-worker/tsconfig.compile.json
  workers/merkle-tree-worker/tsconfig.json
Labels: enhancement, needs rebase

#288 fix: build merkle-tree pkg before running static analysis checks in CI
  .github/workflows/static-analysis.yml
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: bug, ci/cd/ct

#293 fix: ignore ``@anonklub/merkle-tree` when publishing packages
  .changeset/config.json
  .github/workflows/release.yml
Labels: bug, ci/cd/ct

#296 fix: build wasm package before install with `devPreinstall` hook
  package.json
  pnpm-lock.yaml
  workers/merkle-tree-worker/package.json
Labels: bug, :technologist: dx

#287 Add Spartan ECDSA Rust circuits
  .changeset/config.json
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
  Cargo.lock
  Cargo.toml
  circuits/halo2/.gitignore
  circuits/halo2/Cargo.toml
  circuits/halo2/README.md
  circuits/halo2/data/merkle.in
  circuits/halo2/examples/merkle.rs
  circuits/halo2/rust-toolchain
  circuits/halo2/rustfmt.toml
  circuits/halo2/src/lib.rs
  circuits/halo2/src/scaffold/cmd.rs
  circuits/halo2/src/scaffold/mod.rs
  circuits/spartan/Cargo.toml
  circuits/spartan/package.json
  circuits/spartan/src/eth_membership.rs
  circuits/spartan/src/lib.rs
  circuits/spartan/src/utils.rs
  merkle-tree-wasm/Cargo.toml
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  workers/merkle-tree-worker/package.json
  workers/merkle-tree-worker/src/index.ts
  workers/merkle-tree-worker/src/worker.ts
Labels: enhancement, :electric_plug: circuits

#295 Integrating the web-workers with the front-end
  @anonklub/proof/package.json
  @anonklub/proof/src/ProofRequest/index.ts
  @anonklub/proof/src/ProofRequest/interface.ts
  package.json
  pnpm-lock.yaml
  ui/next.config.js
  ui/package.json
  ui/src/app/prove/result/page.tsx
  ui/src/hooks/useMerkleTreeWorker.ts
  ui/src/hooks/useProofRequest.ts
  ui/src/hooks/useProofResult.ts
  ui/src/hooks/useSpartanEcdsaWorker.ts
  ui/tsconfig.json
  workers/merkle-tree-worker/src/interface.ts
  workers/spartan-ecdsa-worker/package.json
  workers/spartan-ecdsa-worker/src/interface.ts
Labels: enhancement, :lipstick: UI, needs rebase

#309 feat(ui): update warning modal
  ui/src/components/SubmitProofRequest.tsx
Labels: :lipstick: UI
